mysite/mysite/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('myform.views',#'myform2.views',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
      url(r'^contact$', 'contact', name='contact'),
      url(r'^contact/$', 'contact', name='contact'),
      url(r'^contact/contact.html$', 'contact', name='contact'),
      url(r'^success$', 'success', name='success'),
      url(r'^glib$', 'contact', name='contact'),
      url(r'^glib/$', 'contact', name='contact'),
)
urlpatterns += patterns('myform2.views',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
      url(r'^successscan$', 'successscan', name='successscan'),
      url(r'^successpower$', 'successpower', name='successpower'),
      url(r'^glibpower/$', 'contact2', name='contact2'),
      url(r'^glibpower$', 'contact2', name='contact2'),
)

mysite/mysite/myform/models.py
from django.db import models
# Create your models here.                                                                                                                                                                                
class Contact(models.Model):
    name = models.CharField(max_length=200)
    firstname = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    message = models.CharField(max_length=1000)

mysite/mysite/myform/views.py
from django.shortcuts import render_to_response, HttpResponseRedirect, HttpResponse, RequestContext
from django import forms
import uhal
import commands
import csv
import time
import binascii
import os

global natmch
global addresse
global regvalue
global manager
global hw
global connect

class ContactForm(forms.Form):
    global hw
    global manager
    natmch = forms.IPAddressField()
    connect = forms.CharField(max_length=100)
    addresse = forms.CharField(max_length=100)
    regvalue = forms.IntegerField()
    cc_myself = forms.BooleanField(required=False)

def contact(request):
        global natmch
        global addresse
        global regvalue
        global toto 
	global manager
	global hw
	global connect        
	toto="JEROME" 
	if request.method == 'POST': # If the form has been submitted...
	    form = ContactForm(request.POST) # A form bound to the POST data
            if form.is_valid(): # All validation rules pass 
               natmch = form.cleaned_data['natmch']
               connect = form.cleaned_data['connect']
               addresse = form.cleaned_data['addresse']
               regvalue = form.cleaned_data['regvalue']
               cc_myself = form.cleaned_data['cc_myself']
	       return HttpResponseRedirect('/success') # Redirect after POST
	else:	
	    form = ContactForm()

	return render_to_response('contact.html', {'form': form, }, context_instance=RequestContext(request))

def success(request):
   global natmch
   global addresse
   global regvalue
   global manager
   global hw
   global connect
   message = "<html><body><head><title>ENVOI ET RECUPERATION SUR GLIB:</title>"
   message+= '<link href="/static/css/style.css" rel="stylesheet" type="text/css" media="screen">'
   message += "<script>function visibilite(thingId) { "
   message += "var targetElement; targetElement = document.getElementById(thingId) ; "
   message += "if (targetElement.style.display == \"none\") {  targetElement.style.display = \"\" ;} else { " 
   message += "targetElement.style.display = \"none\" ; "
   message += "} } </script></head>"
   message +="<center><h1>ENVOI ET RECUPERATION SUR GLIB:</h1><div id=\"info\">"
   message += str(connect) +" via NAT-MCH IP:"+str(natmch) +"</div></center><br>"
   message += "<br><a href='' id=\"menu\" onclick=\"javascript:visibilite('id_div_eglib');return false;\">Envoi GLIB</a>"
   message += " | <a href='' id=\"menu\" onclick=\"javascript:visibilite('id_div_rglib');return false;\">Récupération GLIB</a>"
   message += " | <a href='' id=\"menu\" onclick=\"javascript:visibilite('id_div_statTCA');return false;\">Statistique &micro;TCA (IP: "+str(natmch)+")</a>"
   message += "<div id=\"id_div_eglib\" style=\"display:none;\">"
   message += "<a href='' id=\"masque\" onclick=\"javascript:visibilite('id_div_eglib');return false;\"><h3>Envoi GLIB</h3></a>"
   message +="<br>IP NAT-MCH="+ str(natmch)
   message +="<br>Connection SLOT="+ str(connect)
   message +="<br>Adresse register="+ str(addresse)
   message +='<div id="value">Register value='+ str(regvalue) +'</div></div>'
   
   manager = uhal.ConnectionManager("file://~/xml/connections.xml")
   hw = manager.getDevice(str(connect))
   ip=hw.uri()
   ip=ip[15::]
   ip=ip[:15:]
   cmdping="ping -c 1 -W 1 "+ ip
   pres_glib = os.system(cmdping)
   if pres_glib==0: 
    message += '<div id="valid_stat">GLIB IS CONNECTED  :-) on ' + ip + '</div>'
   else:
    message += '<div id="error_stat">GLIB IS NOT CONNECTED  :-( on '+ ip +'</div>'	
   #hw = manager.getDevice("GLIBboardfake")
   #hw = manager.getDevice("GLIBboard")
   #hw = manager.getDevice("localhost")	
   monnode = str(addresse)
   mystr=monnode.split(".")
   mylen=len(mystr)
   node="TOTOT"
   perm="READ"
   message += "<div id=\"id_div_rglib\" style=\"display:none;\">"
   message += "<a href='' id=\"masque\" onclick=\"javascript:visibilite('id_div_rglib');return false;\"><h3>Récupération GLIB:</h3></a>"
   #message += "<br>mylen="+str(mylen)
   #message += "<br>mystr="+str(mystr)
   if mylen == 1:
    node= hw.getNode(mystr[0])
    perm =str(hw.getNode(mystr[0]).getPermission())
   elif mylen == 2:
    node= hw.getNode(mystr[0]).getNode(mystr[1])
    perm =str(hw.getNode(mystr[0]).getNode(mystr[1]).getPermission())
   elif mylen == 3:
    node= hw.getNode(mystr[0]).getNode(mystr[1]).getNode(mystr[2])
    perm =str(hw.getNode(mystr[0]).getNode(mystr[1]).getNode(mystr[2]).getPermission())  
   if perm == 'READ':
    message += "<br>Register READ ONLY  :do nothing"
   elif perm == 'READWRITE':
    message += "<br>Register READWRITE  : write ok"
    if mylen == 1:
     node= hw.getNode(mystr[0])
     #hw.getNode(mystr[0]).write(regvalue)
     message +='<br><div id="error">NOT YET IMPLEMENTED : NOT Working at this time</div>'
    elif mylen == 2:
     node= hw.getNode(mystr[0]).getNode(mystr[1])
     ##hw.getNode(mystr[0]).getNode(mystr[1]).write(regvalue)
     #node.write(regvalue)
     message +='<br><div id="error">NOT YET IMPLEMENTED : NOT Working at this time</div>'
    elif mylen == 3:
     node= hw.getNode(mystr[0]).getNode(mystr[1]).getNode(mystr[2])
     message +='<br><div id="error">NOT YET IMPLEMENTED : NOT Working at this time</div>'
     #node.write(regvalue)
     #hw.getNode(mystr[0]).getNode(mystr[1]).getNode(mystr[2]).write(regvalue)
   elif perm == 'WRITE':
    message += "<br>WRITE ONLY"
    if mylen == 1:
     node= hw.getNode(mystr[0])
     hw.getNode(mystr[0]).write(regvalue)
    elif mylen == 2:
     node= hw.getNode(mystr[0]).getNode(mystr[1])
     node.write(regvalue)
     #hw.getNode(mystr[0]).getNode(mystr[1]).write(regvalue)
    elif mylen == 3:
     node= hw.getNode(mystr[0]).getNode(mystr[1]).getNode(mystr[2])
     node.write(regvalue)
     #hw.getNode(mystr[0]).getNode(mystr[1]).getNode(mystr[2]).write(regvalue)
    #node.write(regvalue)
   
  # Read the value back.
  # NB: the reg variable below is a uHAL "ValWord", not just a simple integer
   if perm == 'READ':
    message += "<br>for read : READ ok"
    if mylen == 1:
     node= hw.getNode(mystr[0])
     reg=hw.getNode(mystr[0]).read()
    elif mylen == 2:
     node= hw.getNode(mystr[0]).getNode(mystr[1])
     #reg=hw.getNode(mystr[0]).getNode(mystr[1]).read()
     reg=node.read() 
    elif mylen == 3:
     node= hw.getNode(mystr[0]).getNode(mystr[1]).getNode(mystr[2])
     #reg=hw.getNode(mystr[0]).getNode(mystr[1]).getNode(mystr[2]).read()
     reg=node.read()
   elif perm == 'READWRITE':
    message += "<br>for read : READWRITE ok"
    if mylen == 1:
     node= hw.getNode(mystr[0])
     reg=hw.getNode(mystr[0]).read()
    elif mylen == 2:
     node= hw.getNode(mystr[0]).getNode(mystr[1])
     #reg=hw.getNode(mystr[0]).getNode(mystr[1]).read()
     reg=node.read()
    elif mylen == 3:
     node= hw.getNode(mystr[0]).getNode(mystr[1]).getNode(mystr[2])
     #reg=hw.getNode(mystr[0]).getNode(mystr[1]).getNode(mystr[2]).read()   
     reg= node.read() 	
  # Send IPbus transactions
   if pres_glib==0: 
    hw.dispatch()
    message += "<div id=\"valid\">Recuperation success</div>"
  # Print the register value to screen as a decimal:
  #print " REG =", reg
    message += "<br>Id : "+str(node.getId())
    message += "<br>Id entiere: "+str(monnode)
    message += '<div id="value">Registre value relecture (en hexa) :'+hex(reg)+"</div>"
    message += '<div id="value">Registre value relecture (en decimal) :'+str(reg.value())+"</div>"
    toto=hex(reg)
    print toto	
    if toto != '0x0':
     if len(toto) > 4:
      print toto[2::].decode('hex')
      message += "<div id=\"value\">Registre value relecture (en ASCII) :"+ toto[2::].decode('hex') +"</div>"
    message += "<br>Addr : "+hex(node.getAddress())
    message += "<br>Mask : "+hex(node.getMask()) 
    message += "<br>Mode : "+ str(node.getMode())   # Mode enum - one of uhal.BlockReadWriteMode.SINGLE (default), INCREMENTAL and NON_INCREMENTAL, or HIERARCHICAL for top-level nodes nesting other nodes.
    message += "<br>Read/write permissions : "+ str(node.getPermission())  # One of uhal.NodePermission.READ, WRITE and READWRITE
    message += "<br>Size (in units of 32-bits) : "+str(node.getSize())     # In units of 32-bits. All single registers and FIFOs have default size of 1
    message += "<br>Tags : "+node.getTags()  # User-definable string from address table - in principle a comma separated list of values	
    message += "</div>"
   else:
    message += '<br><div id="error">Dispatch NOT OK => GLIB NOT PRESENT</div></div>'
  # Print the register value to screen in hex:
  #print " REG =", hex(reg)
  # Get the underlying integer value from the reg "ValWord"
  #value = int(reg) # Equivalent to reg.value()
   cmdping="ping -c 1 -W 1 "+natmch
   x = os.system(cmdping)
   #x=0 # FORCAGE VALEUR
   if x==0: 
    message += '<div id="valid_stat">NAT-MCH IS CONNECTED  :-) on ' + str(natmch)+'</div>'
   else:
    message += '<div id="error_stat">NAT-MCH IS NOT CONNECTED  :-( on ' + str(natmch)+'</div>'
    message += "<div id=\"id_div_statTCA\" style=\"display:none;\">"
    message += ""
    message += "<a href='' id=\"masque\" onclick=\"javascript:visibilite('id_div_statTCA');return false;\"><h3>Statistique &micro;TCA</h3></a>"
   if x==0:
    cmdipmi="ipmitool -H "+str(natmch) +" -P '' -c sdr > /home/xtaldaq/mysite/myform/output.csv"
    res=commands.getstatusoutput(cmdipmi)
    time.sleep(1)
    cr = csv.reader(open("/home/xtaldaq/mysite/myform/output.csv","r"))
    #message = "<table  BORDER='1'><tr><th>ID</th><th>ID2</th><th>ID3</th></tr>" 
    dt=time.strftime('%d/%m/%y %H:%M',time.localtime()) 
    message += "<div id=\"id_div_statTCA\" style=\"display:none;\">"
    message += ""
    message += "<a href='' id=\"masque\" onclick=\"javascript:visibilite('id_div_statTCA');return false;\"><h3>Statistique &micro;TCA</h3></a>"
    message += "<br><center><bold>CRATE GLIB via NAT-MCH IP="+ str(natmch) +"</bold><div id=\"valid\"> Maj:"+ dt +" </div><table><tr><th>Sensor</th><th>Valeur</th><th>Etat/Unité</th></tr>"
    for row in cr:

mysite/mysite/myform/templates/contact-GLIB.html
<center><h2>GLIB CONTROL REGISTER</h2></center>
<form action="/glib" method="post">{% csrf_token %}
<br>Register choice
<select id="id_addresse" name="addresse" onChange="combo(this, 'id_addresse')">
<option>
REG
</option>
<option>
REG2.subreg
</option>
<option>
board_id
</option>
<option>
ctrl_sram
</option>
<option>
ctrl_sram.flash_select
</option>
<option>
ctrl_sram.sram1_bist_run
</option>
<option>
ctrl_sram.sram1_user_logic
</option>
<option>
ctrl_sram.sram2_bist_run
</option>
<option>
ctrl_sram.sram2_user_logic
</option>
<option>
firm_id
</option>
<option>
firm_id.firmware_dd
</option>
<option>
firm_id.firmware_mm
</option>
<option>
firm_id.firmware_ver
</option>
<option>
firm_id.firmware_yy
</option>
<option>
freq_ttc_fmc
</option>
<option>
sram1
</option>
<option>
sram2
</option>
<option>
status
</option>
<option>
status.cdce_lock
</option>
<option>
status.fmc1_present
</option>
<option>
status.fmc2_present
</option>
<option>
status.fpga_reset
</option>
<option>
status.gbe_int
</option>
<option>
status.glib_sfp1_mod_abs
</option>
<option>
status.glib_sfp1_rxlos
</option>
<option>
status.glib_sfp1_status
</option>
<option>
status.glib_sfp1_txfault
</option>
<option>
status.glib_sfp2_mod_abs
</option>
<option>
status.glib_sfp2_rxlos
</option>
<option>
status.glib_sfp2_status
</option>
<option>
status.glib_sfp2_txfault
</option>
<option>
status.glib_sfp3_mod_abs
</option>
<option>
status.glib_sfp3_rxlos
</option>
<option>
status.glib_sfp3_status
</option>
<option>
status.glib_sfp3_txfault
</option>
<option>
status.glib_sfp4_mod_abs
</option>
<option>
status.glib_sfp4_rxlos
</option>
<option>
status.glib_sfp4_status
</option>
<option>
status.glib_sfp4_txfault
</option>
<option>
status.v6_cpld
</option>
<option>
sys_id
</option>
<option>
user_wb_ttc_fmc_regs
</option>
<option>
user_wb_ttc_fmc_regs.flags
</option>
<option>
user_wb_ttc_fmc_regs.flags.FSM1_flag
</option>
<option>
user_wb_ttc_fmc_regs.flags.FSM2_flag
</option>
<option>
user_wb_ttc_fmc_regs.flags.SRAM1_full
</option>
<option>
user_wb_ttc_fmc_regs.flags.SRAM2_full
</option>
<option>
user_wb_ttc_fmc_regs.i2c_command
</option>
<option>
user_wb_ttc_fmc_regs.i2c_reply
</option>
<option>
user_wb_ttc_fmc_regs.i2c_settings
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.ACQ_MODE
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.CBC_DATA_GENE
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.CBC_DATA_PACKET_NUMBER
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.INT_TRIGGER_FREQ
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.PC_config_ok
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.SPURIOUS_FRAME
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.SRAM1_end_readout
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.SRAM2_end_readout
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.TRIGGER_SEL
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands2
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands2.clock_shift
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands2.negative_logic_CBC
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands2.negative_logic_sTTS
</option>
<option>
user_wb_ttc_fmc_regs.status_flags
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.FSM_sTTS_ctrl
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.cdr_clk_locked
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.cdr_lol
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.cdr_los
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.fifo1_full
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.fifo2_full
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.sTTS_code
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.spurious_frame
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s10
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s11
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s20
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s21
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s30
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s31
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s40
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s41
</option>
<option>
user_wb_ttc_fmc_regs.user_board_id
</option>
<option>
user_wb_ttc_fmc_regs.user_sys_id
</option>
<option>
user_wb_ttc_fmc_regs.user_version
</option>
</select>
<br>Register Value<br><input id="id_regvalue" name="regvalue" type="text">
<br><input type="submit" value="Submit" />
</form>

mysite/mysite/myform/templates/contact-ori.html
<center><h2>GLIB CONTROL REGISTER</h2></center>
<form action="/glib" method="post">{% csrf_token %}
{{ form.as_p }}
<select id="id_addresse" name="addresse" onChange="combo(this, 'id_addresse')">
<option>
REG
</option>
<option>
REG2.subreg
</option>
<option>
board_id
</option>
<option>
ctrl_sram
</option>
<option>
ctrl_sram.flash_select
</option>
<option>
ctrl_sram.sram1_bist_run
</option>
<option>
ctrl_sram.sram1_user_logic
</option>
<option>
ctrl_sram.sram2_bist_run
</option>
<option>
ctrl_sram.sram2_user_logic
</option>
<option>
firm_id
</option>
<option>
firm_id.firmware_dd
</option>
<option>
firm_id.firmware_mm
</option>
<option>
firm_id.firmware_ver
</option>
<option>
firm_id.firmware_yy
</option>
<option>
freq_ttc_fmc
</option>
<option>
sram1
</option>
<option>
sram2
</option>
<option>
status
</option>
<option>
status.cdce_lock
</option>
<option>
status.fmc1_present
</option>
<option>
status.fmc2_present
</option>
<option>
status.fpga_reset
</option>
<option>
status.gbe_int
</option>
<option>
status.glib_sfp1_mod_abs
</option>
<option>
status.glib_sfp1_rxlos
</option>
<option>
status.glib_sfp1_status
</option>
<option>
status.glib_sfp1_txfault
</option>
<option>
status.glib_sfp2_mod_abs
</option>
<option>
status.glib_sfp2_rxlos
</option>
<option>
status.glib_sfp2_status
</option>
<option>
status.glib_sfp2_txfault
</option>
<option>
status.glib_sfp3_mod_abs
</option>
<option>
status.glib_sfp3_rxlos
</option>
<option>
status.glib_sfp3_status
</option>
<option>
status.glib_sfp3_txfault
</option>
<option>
status.glib_sfp4_mod_abs
</option>
<option>
status.glib_sfp4_rxlos
</option>
<option>
status.glib_sfp4_status
</option>
<option>
status.glib_sfp4_txfault
</option>
<option>
status.v6_cpld
</option>
<option>
sys_id
</option>
<option>
user_wb_ttc_fmc_regs
</option>
<option>
user_wb_ttc_fmc_regs.flags
</option>
<option>
user_wb_ttc_fmc_regs.flags.FSM1_flag
</option>
<option>
user_wb_ttc_fmc_regs.flags.FSM2_flag
</option>
<option>
user_wb_ttc_fmc_regs.flags.SRAM1_full
</option>
<option>
user_wb_ttc_fmc_regs.flags.SRAM2_full
</option>
<option>
user_wb_ttc_fmc_regs.i2c_command
</option>
<option>
user_wb_ttc_fmc_regs.i2c_reply
</option>
<option>
user_wb_ttc_fmc_regs.i2c_settings
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.ACQ_MODE
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.CBC_DATA_GENE
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.CBC_DATA_PACKET_NUMBER
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.INT_TRIGGER_FREQ
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.PC_config_ok
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.SPURIOUS_FRAME
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.SRAM1_end_readout
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.SRAM2_end_readout
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands.TRIGGER_SEL
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands2
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands2.clock_shift
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands2.negative_logic_CBC
</option>
<option>
user_wb_ttc_fmc_regs.pc_commands2.negative_logic_sTTS
</option>
<option>
user_wb_ttc_fmc_regs.status_flags
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.FSM_sTTS_ctrl
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.cdr_clk_locked
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.cdr_lol
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.cdr_los
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.fifo1_full
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.fifo2_full
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.sTTS_code
</option>
<option>
user_wb_ttc_fmc_regs.status_flags.spurious_frame
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s10
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s11
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s20
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s21
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s30
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s31
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s40
</option>
<option>
user_wb_ttc_fmc_regs.ttc_fmc_reg_ctrl.ttc_fmc_s41
</option>
<option>
user_wb_ttc_fmc_regs.user_board_id
</option>
<option>
user_wb_ttc_fmc_regs.user_sys_id
</option>
<option>
user_wb_ttc_fmc_regs.user_version
</option>
</select>
<input id="id_regvalue" name="regvalue" type="text">
<input type="submit" value="Submit" />
</form>